name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
